POST http://167.172.207.18:3000/tasks
Content-Type: application/json

{
  "name": "Nature Home Page",
  "url": "nature.com",
  "standard": "WCAG2AA"
}

###
POST http://127.0.0.1:3000/tasks/5e56b2ee5164f8123cccd422/run

###
GET http://167.172.207.18:3000/tasks/5e552f6a598b3307f9522472/results?full=true

###
